name: ics-water-simulation

services:
  tank-sim:
    build: ./tank-sim/app
    container_name: tank-sim
    restart: unless-stopped
    networks:
      ot_hmi_net:
        ipv4_address: 169.254.45.60
    # keep ports closed unless you truly need host access
    # ports:
    #   - "5000:5000"

  revpi-twin:
    image: nodered/node-red:latest
    container_name: revpi-twin
    restart: unless-stopped
    networks:
      ot_hmi_net:
        ipv4_address: 169.254.45.52
      rm_net:
        ipv4_address: 158.39.170.5
    volumes:
      - ./node-red-flows:/data
      
  hmi:
    image: nginx:alpine
    container_name: hmi
    restart: unless-stopped
    depends_on:
      - revpi-twin
    networks:
      ot_hmi_net:
        ipv4_address: 169.254.45.56
    ports:
      - "8080:80"
    volumes:
      - ./hmi/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  ot_hmi_net:
    driver: bridge
    ipam:
      config:
        - subnet: 169.254.45.0/24

  rm_net:
    driver: bridge
    ipam:
      config:
        - subnet: 158.39.170.0/24
