services:
  revpi-twin:
    image: nodered/node-red:latest
    container_name: revpi-twin
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
    networks:
      - ot_net

networks:
  ot_net:
    external: true
